### ISSUE TITLE
After upgrading to V7 Jest tests fail

### ISSUE THREAD

**Issue by marnixhoh** [socketio/socket.io-redis-adapter#413]
I just updated from `socket.io-redis` `6.0.1` to `@socket.io/redis-adapter` `7.0.0`. In development everything works fine, however when running the test suite (Jest), I get the following error:

`TypeError: socket.client.writeToEngine is not a function`

Just to be clear, before the update everything was working as expected in both development and the test environment.

Below is my setup in case it helps:

```
const Redis = require('ioredis')
const redisAdapter = require('@socket.io/redis-adapter')

const redis = new Redis.Cluster(startupNodes, {
    slotsRefreshTimeout: 2000,
    dnsLookup: (address, callback) => callback(null, address)
})

const subClient = new Redis.Cluster(startupNodes, {
    slotsRefreshTimeout: 2000,
    dnsLookup: (address, callback) => callback(null, address)
})
const ioAdapter = redisAdapter(redis, subClient)

module.exports = redis
module.exports.ioAdapter = ioAdapter
```

**Comment by marnixhoh** [comment]
I just found the solution... After updating `socket.io` (to `4.1.3`) & `socket.io-client` (to `4.1.3`) the above error disappeared.

I hope it might help someone else.
