### ISSUE TITLE
Doesn't work with node-redis v4.0.0

### ISSUE THREAD

**Issue by Xairoo** [socketio/socket.io-redis-adapter#417]
I updated [node-redis](https://github.com/NodeRedis/node-redis) from v3.1.2 to 4.0.0 on my node client and socket.io stopped working. First emit is send, then it crashes.

Node client:
```
Error: Got an unexpected reply from Redis
    at RedisCommandsQueue._RedisCommandsQueue_shiftWaitingForReply
```

Socket.io server (redis 3.1.2):
```
node_modules\notepack.io\lib\decode.js:246
    throw new Error((buffer.length - decoder.offset) + ' trailing bytes');
```

Running Socket.io server with redis 4.0.0:
```
node_modules\@socket.io\redis-adapter\dist\index.js:64
        this.subClient.psubscribe(this.channel + "*", onError);
                       ^

TypeError: this.subClient.psubscribe is not a function
    at new RedisAdapter
```

**Comment by darrachequesne** [comment]
Support for `redis@4` was added in release 7.1.0: https://github.com/socketio/socket.io-redis-adapter/releases/tag/7.1.0
